graph LR
    AccessControlModule-->ConfigHostModule
  AccessControlModule-->ConfigModule
  AccessControlModule-->MailerCoreModule
  AccessControlModule-->RedisCoreModule
  AccessControlModule-->ScheduleModule
  AccessControlModule-->SequelizeCoreModule
  AppModule-->AuthModule
  AppModule-->ChatModule
  AppModule-->ClassroomModule
  AppModule-->ConfigHostModule
  AppModule-->ConfigModule
  AppModule-->FlashcardModule
  AppModule-->MailerCoreModule
  AppModule-->MailerModule
  AppModule-->PaymentModule
  AppModule-->RedisCoreModule
  AppModule-->ReportsModule
  AppModule-->ScheduleModule
  AppModule-->SequelizeCoreModule
  AppModule-->SequelizeModule
  AppModule-->StatisticsModule
  AppModule-->TestsModule
  AppModule-->UsersModule
  AuthModule-->ConfigHostModule
  AuthModule-->ConfigModule
  AuthModule-->JwtModule
  AuthModule-->MailerCoreModule
  AuthModule-->PassportModule
  AuthModule-->RedisCoreModule
  AuthModule-->RedisModule
  AuthModule-->ScheduleModule
  AuthModule-->SequelizeCoreModule
  AuthModule-->UsersModule
  ChatModule-->AccessControlModule
  ChatModule-->ConfigHostModule
  ChatModule-->ConfigModule
  ChatModule-->MailerCoreModule
  ChatModule-->RedisCoreModule
  ChatModule-->ScheduleModule
  ChatModule-->SequelizeCoreModule
  ChatModule-->SequelizeModule
  ChatModule-->VectorStoreModule
  ClassroomModule-->ConfigHostModule
  ClassroomModule-->ConfigModule
  ClassroomModule-->MailerCoreModule
  ClassroomModule-->MulterModule
  ClassroomModule-->RedisCoreModule
  ClassroomModule-->ScheduleModule
  ClassroomModule-->SequelizeCoreModule
  ClassroomModule-->SequelizeModule
  ClassroomModule-->TestsModule
  ClassroomModule-->UploadModule
  ConfigHostModule-->ConfigModule
  ConfigHostModule-->MailerCoreModule
  ConfigHostModule-->RedisCoreModule
  ConfigHostModule-->ScheduleModule
  ConfigHostModule-->SequelizeCoreModule
  ConfigModule-->ConfigHostModule
  ConfigModule-->ConfigModule
  ConfigModule-->MailerCoreModule
  ConfigModule-->RedisCoreModule
  ConfigModule-->ScheduleModule
  ConfigModule-->SequelizeCoreModule
  DiscoveryModule-->ConfigHostModule
  DiscoveryModule-->ConfigModule
  DiscoveryModule-->MailerCoreModule
  DiscoveryModule-->RedisCoreModule
  DiscoveryModule-->ScheduleModule
  DiscoveryModule-->SequelizeCoreModule
  FlashcardModule-->ConfigHostModule
  FlashcardModule-->ConfigModule
  FlashcardModule-->MailerCoreModule
  FlashcardModule-->RedisCoreModule
  FlashcardModule-->ScheduleModule
  FlashcardModule-->SequelizeCoreModule
  FlashcardModule-->SequelizeModule
  JwtModule-->ConfigHostModule
  JwtModule-->ConfigModule
  JwtModule-->MailerCoreModule
  JwtModule-->RedisCoreModule
  JwtModule-->ScheduleModule
  JwtModule-->SequelizeCoreModule
  MailerCoreModule-->ConfigHostModule
  MailerCoreModule-->ConfigModule
  MailerCoreModule-->RedisCoreModule
  MailerCoreModule-->ScheduleModule
  MailerCoreModule-->SequelizeCoreModule
  MailerModule-->ConfigHostModule
  MailerModule-->ConfigModule
  MailerModule-->MailerCoreModule
  MailerModule-->RedisCoreModule
  MailerModule-->ScheduleModule
  MailerModule-->SequelizeCoreModule
  MulterModule-->ConfigHostModule
  MulterModule-->ConfigModule
  MulterModule-->MailerCoreModule
  MulterModule-->RedisCoreModule
  MulterModule-->ScheduleModule
  MulterModule-->SequelizeCoreModule
  PassportModule-->ConfigHostModule
  PassportModule-->ConfigModule
  PassportModule-->MailerCoreModule
  PassportModule-->RedisCoreModule
  PassportModule-->ScheduleModule
  PassportModule-->SequelizeCoreModule
  PaymentModule-->AccessControlModule
  PaymentModule-->ClassroomModule
  PaymentModule-->ConfigHostModule
  PaymentModule-->ConfigModule
  PaymentModule-->MailerCoreModule
  PaymentModule-->RedisCoreModule
  PaymentModule-->ScheduleModule
  PaymentModule-->SequelizeCoreModule
  PaymentModule-->SequelizeModule
  PaymentModule-->UsersModule
  RedisCoreModule-->ConfigHostModule
  RedisCoreModule-->ConfigModule
  RedisCoreModule-->MailerCoreModule
  RedisCoreModule-->ScheduleModule
  RedisCoreModule-->SequelizeCoreModule
  RedisModule-->ConfigHostModule
  RedisModule-->ConfigModule
  RedisModule-->MailerCoreModule
  RedisModule-->RedisCoreModule
  RedisModule-->ScheduleModule
  RedisModule-->SequelizeCoreModule
  ReportsModule-->AccessControlModule
  ReportsModule-->ConfigHostModule
  ReportsModule-->ConfigModule
  ReportsModule-->MailerCoreModule
  ReportsModule-->RedisCoreModule
  ReportsModule-->ScheduleModule
  ReportsModule-->SequelizeCoreModule
  ReportsModule-->SequelizeModule
  ReportsModule-->UsersModule
  ScheduleModule-->ConfigHostModule
  ScheduleModule-->ConfigModule
  ScheduleModule-->DiscoveryModule
  ScheduleModule-->MailerCoreModule
  ScheduleModule-->RedisCoreModule
  ScheduleModule-->ScheduleModule
  ScheduleModule-->SequelizeCoreModule
  SequelizeCoreModule-->ConfigHostModule
  SequelizeCoreModule-->ConfigModule
  SequelizeCoreModule-->MailerCoreModule
  SequelizeCoreModule-->RedisCoreModule
  SequelizeCoreModule-->ScheduleModule
  SequelizeModule-->ConfigHostModule
  SequelizeModule-->ConfigModule
  SequelizeModule-->MailerCoreModule
  SequelizeModule-->RedisCoreModule
  SequelizeModule-->ScheduleModule
  SequelizeModule-->SequelizeCoreModule
  StatisticsModule-->AccessControlModule
  StatisticsModule-->ConfigHostModule
  StatisticsModule-->ConfigModule
  StatisticsModule-->MailerCoreModule
  StatisticsModule-->RedisCoreModule
  StatisticsModule-->ScheduleModule
  StatisticsModule-->SequelizeCoreModule
  StatisticsModule-->SequelizeModule
  TestsModule-->ClassroomModule
  TestsModule-->ConfigHostModule
  TestsModule-->ConfigModule
  TestsModule-->MailerCoreModule
  TestsModule-->RedisCoreModule
  TestsModule-->ScheduleModule
  TestsModule-->SequelizeCoreModule
  TestsModule-->SequelizeModule
  TestsModule-->UsersModule
  UploadModule-->ConfigHostModule
  UploadModule-->ConfigModule
  UploadModule-->MailerCoreModule
  UploadModule-->MulterModule
  UploadModule-->RedisCoreModule
  UploadModule-->ScheduleModule
  UploadModule-->SequelizeCoreModule
  UsersModule-->ConfigHostModule
  UsersModule-->ConfigModule
  UsersModule-->MailerCoreModule
  UsersModule-->RedisCoreModule
  UsersModule-->ScheduleModule
  UsersModule-->SequelizeCoreModule
  UsersModule-->SequelizeModule
  UsersModule-->TestsModule
  VectorStoreModule-->ConfigHostModule
  VectorStoreModule-->ConfigModule
  VectorStoreModule-->MailerCoreModule
  VectorStoreModule-->RedisCoreModule
  VectorStoreModule-->ScheduleModule
  VectorStoreModule-->SequelizeCoreModule