graph LR
    AppModule-->AuthModule
  AppModule-->ConfigHostModule
  AppModule-->ConfigModule
  AppModule-->MailerCoreModule
  AppModule-->MailerModule
  AppModule-->RedisCoreModule
  AppModule-->SequelizeCoreModule
  AppModule-->SequelizeModule
  AppModule-->UsersModule
  AuthModule-->ConfigHostModule
  AuthModule-->ConfigModule
  AuthModule-->JwtModule
  AuthModule-->MailerCoreModule
  AuthModule-->PassportModule
  AuthModule-->RedisCoreModule
  AuthModule-->RedisModule
  AuthModule-->SequelizeCoreModule
  AuthModule-->UsersModule
  ConfigHostModule-->ConfigModule
  ConfigHostModule-->MailerCoreModule
  ConfigHostModule-->RedisCoreModule
  ConfigHostModule-->SequelizeCoreModule
  ConfigModule-->ConfigHostModule
  ConfigModule-->ConfigModule
  ConfigModule-->MailerCoreModule
  ConfigModule-->RedisCoreModule
  ConfigModule-->SequelizeCoreModule
  JwtModule-->ConfigHostModule
  JwtModule-->ConfigModule
  JwtModule-->MailerCoreModule
  JwtModule-->RedisCoreModule
  JwtModule-->SequelizeCoreModule
  MailerCoreModule-->ConfigHostModule
  MailerCoreModule-->ConfigModule
  MailerCoreModule-->RedisCoreModule
  MailerCoreModule-->SequelizeCoreModule
  MailerModule-->ConfigHostModule
  MailerModule-->ConfigModule
  MailerModule-->MailerCoreModule
  MailerModule-->RedisCoreModule
  MailerModule-->SequelizeCoreModule
  PassportModule-->ConfigHostModule
  PassportModule-->ConfigModule
  PassportModule-->MailerCoreModule
  PassportModule-->RedisCoreModule
  PassportModule-->SequelizeCoreModule
  RedisCoreModule-->ConfigHostModule
  RedisCoreModule-->ConfigModule
  RedisCoreModule-->MailerCoreModule
  RedisCoreModule-->SequelizeCoreModule
  RedisModule-->ConfigHostModule
  RedisModule-->ConfigModule
  RedisModule-->MailerCoreModule
  RedisModule-->RedisCoreModule
  RedisModule-->SequelizeCoreModule
  SequelizeCoreModule-->ConfigHostModule
  SequelizeCoreModule-->ConfigModule
  SequelizeCoreModule-->MailerCoreModule
  SequelizeCoreModule-->RedisCoreModule
  SequelizeModule-->ConfigHostModule
  SequelizeModule-->ConfigModule
  SequelizeModule-->MailerCoreModule
  SequelizeModule-->RedisCoreModule
  SequelizeModule-->SequelizeCoreModule
  UsersModule-->ConfigHostModule
  UsersModule-->ConfigModule
  UsersModule-->MailerCoreModule
  UsersModule-->RedisCoreModule
  UsersModule-->SequelizeCoreModule
  UsersModule-->SequelizeModule