version: '3'
services:
    postgres:
        image: postgres:16
        container_name: market-postgres
        ports:
            - '${DB_PORT}:5432'
        restart: always
        volumes:
            - ./docker/postgres:/var/lib/postgresql/data
        logging:
            driver: 'json-file'
            options:
                # need to tune later after running in production
                max-size: '100m'
                max-file: '20'
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: tiawai-server
        restart: unless-stopped
        depends_on:
            - postgres
        ports:
            - ${SERVER_PORT}:8080
    redis:
        image: redis:alpine
        ports:
            - '${REDIS_PORT}:6379'
        command: redis-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - redis_data:/data
        networks:
            - app_network

volumes:
    redis_data:
        driver: local
    postgres_data:
        driver: local

networks:
    app_network:
        driver: bridge
